### ISSUE TITLE
Why does this exist

### ISSUE THREAD

**Issue by koolamusic** [gravel-form/gravel#2]
Somehow I always love to ask this questions, I know you've spent a lot of time working on this, and I recently came across https://knilink.github.io/react-jsonschema-formbuilder/#! which is super awesome. I can't tell you how much time you're going to save I and my team.

So with interest I really would love to know, why does gravel exist?
What was/is the problem you were trying to solve?

Best regards

**Comment by knilink** [comment]
Hi @koolamusic,

Thank you for your interest. Here's the story about this project.

The thought started [here](https://github.com/rjsf-team/react-jsonschema-form/issues/637). I brought that up because I in my opinion using a function would give users more control, and also at that time I wanted to override the built-in `getWidget` function which would [throw](https://github.com/rjsf-team/react-jsonschema-form/blob/2c41db361718b65c4664bb17e080a450f47ce60f/packages/core/src/utils.js#L153) when no widget found. Because the `getWidget` is invoked in the render function so the exception would break the whole component tree, and widget not found is a pretty common situation in the form build while user is in the middle of editing the schema. So I would like `getWidget` to return a default fall back component instead.

In rjsf , I've been seeing people come up with all sort of different requirements. It's painful to spend 80% of the effort to cover those 20% corner cases. Eventually, I feel rjsf may become too complex that most people are not able to figure out how to customize it themselves to meet their own requirements.

One day, I revisited that `widgets` function proposal issue. I asked myself "is there any better form of the `widgets` function?", "looks like it could be just a render function returning a react element instead of a component. this looks funny because in this case the form theoretically has only 1 widget but still doing the same thing". "just one big renderWidget may be hard to maintain. If I rename the `builtInWidgets` parameter to `next`, then I can break it down to multiple middlewares and compose them like how `express` does". 

Latter I realized not just the widgets, all other parts of the form such as templates, submit button, validation, can all be abstracted as middlewares. This become more flexible and solve the pain point I had with rjsf. I can make any minor adjustment easily with this middleware solution. I can put a `friendlyErrorMessageMw` after the `validationMw` to override the original error message. If I want to validate on the server side, I can implement an `asyncValidationMw` and intercept the submit handler. If I don't want the submit button, I can simply remove `SubmitButtonMw` from the list. Advance features such as `anyOf`, `oneOf` can be managed as standalone modules and install as need which help reducing the bundle file size. All middlewares share the same props which make it easy to learn. Developers can also publish their own awesome middlewares. 

That's how I started this project.

Best Regards,

**Comment by koolamusic** [comment]
Thanks for the response, this is really good. I have come across the same problems you've mentioned, and yeah I buy into giving the developers more power to build their own middlewares on top of this layer. At the end `rjsf` would be a specification we can use to generate forms, but without the tight coupling.

- Fallback Component is required, sometimes I still get JSON parse errors in production when networks are slow, I've had to work around that
- Functional validation is great as well as having control over the `SubmitButton` can improve UX tremendously especially in Section or Multi page form scenarios

Thanks for making this, I will find time to use it and also make my own contributions.
